- hosts: slavenodes
  vars_files:
  - varFile
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     cat join_token | tail -2 > out.sh
     echo "--ignore-preflight-errors=all" | cat >> out.sh
     sh out.sh
     
     
#loop:
     # echo '\ --node-name node{{ item }}' | cat >> out.sh
     #- one
     #- two
     #loop: "{{ groups['slavenodes'] }}"
     # loop_control:
     # index_var: nodeidx
